# File Configuration
files:
  ignore:
    - 'scss/_wysiwyg.scss'
    - 'scss/_generic.scss'

# Rule Configuration
rules:
  border-zero:
    - 1
    -
      convention: none
  class-name-format:
  - 1
  -
    convention: hyphenatedbem
  extends-before-mixins: 2
  extends-before-declarations: 2
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 0
  leading-zero:
    - 1
    -
      include: true
  placeholder-in-extend: 2
  mixins-before-declarations: 0
  no-color-literals:
    - 1
    -
      allow-rgba: true
  no-css-comments: 0
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  no-qualifying-elements: 0
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 4
  property-sort-order: 0
  pseudo-element: 0